# **Welcome to Thea's Github**

> Hello my name is Thea! You can call me Thea1396.

## School Related Links 
[`LMS PORTAL`](https://jhsportal.adnu.edu.ph/)
[`ADNU JHS ONLINE SYSTEM`](https://jhsos.adnu.edu.ph/)
